services:
  _defaults:
    autoconfigure: true

  Kunstmaan\AnomyBundle\Command\AnonymizeDatabaseCommand:
    arguments:
      - '%kunstmaan_anomy.backup_dir%'
      - '%kunstmaan_anomy.config_file%'
      - '@database.connection.anomy'

  database.connection.anomy:
    class: Doctrine\DBAL\Connection
    factory: Doctrine\DBAL\DriverManager::getConnection
    arguments:
      $params:
        driver:    pdo_mysql
        host:      '%database_host%'
        port:      ~
        user:      '%kunstmaan_anomy.database_user%'
        password:  '%kunstmaan_anomy.database_password%'
        dbname:    'anomy'
        charset:   UTF8
